- hosts: localhost
  roles:
     - role: agent
       zabbix_agent_server: 192.168.25.17
       zabbix_agent_serveractive: 192.168.25.17
       zabbix_url: https://zabbix-lab.capes.gov.br
       zabbix_api_use: true # use zabbix_api_create_hosts and/or zabbix_api_create_hostgroup from 0.8.0
       zabbix_api_user: Admin
       zabbix_api_pass: zabbix
       zabbix_create_host: present
       zabbix_host_groups:
         - Linux Servers
       zabbix_link_templates:
         - Template OS Linux
         - Apache APP Template
       zabbix_macros:
         - macro_key: apache_type
           macro_value: reverse_proxy