- hosts: localhost
  roles:
     - role: agent
       zabbix_agent_server: 172.19.X.X
       zabbix_agent_serveractive: 172.19.X.X
       zabbix_url: https://zabbix-lab.capes.gov.br
       zabbix_api_use: true # Para utilizar a API para conexão com zabbix server
       zabbix_api_user: Admin
       zabbix_api_pass: zabbix
       zabbix_api_create_hostgroup: True #True/False - alem da instalação do agent criar/adiciona a um hostgroup
       zabbix_api_create_hosts: True #True/False - alem da instalação do agent criar/atualizar host
       zabbix_create_host: present
       zabbix_host_groups:
         - Linux Servers
       zabbix_link_templates:
         - Template OS Linux by Zabbix agent
         - Template App Zabbix Server
       #zabbix_macros:
       #  - macro_key: apache_type
       #    macro_value: reverse_proxy