---
# tasks file for ansible-zabbix
- name: Install common packages
  include_tasks: "common.yml"
   
- name: Install Zabbix Server
  include: "Zbx-server.yml"

- name: Install Frontend
  include: "Zbx-frontend.yml"
  