- name: Set some fact
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: Install Zabbix Repo.
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"

- name: Install package Zabbix
  yum:
    name:
      - zabbix-web-{{ zabbix_server_database }}
      - zabbix-get
      - zabbix-sender
      - zabbix-nginx-conf

- name: Make sure nginx service is running
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Copy web.zabbix.conf template 
  template:
    src: ./roles/zabbix-all/templates/zabbix_web.conf.j2
    dest: /etc/nginx/conf.d/zabbix.conf
- name: Copy cert file
  template:
    src: ./roles/zabbix-all/files/server.key
    dest: /etc/pki/server.key
- name: Copy cert key file 
  template:
    src: ./roles/zabbix-all/files/server.crt
    dest: /etc/pki/server.crt
- name: zabbix.conf.php
  template:
    src: ./roles/zabbix-all/templates/zabbix_front_config.j2
    dest: /etc/zabbix/web/zabbix.conf.php
- name: zabbix.conf.php
  template:
    src: ./roles/zabbix-all/templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  
- name: Create firewall rule
  firewalld:
    port: 80/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Firewalld reload
  command: firewall-cmd --reload